<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Version>0.0.0.16</Version>
    <Description>A pose browser to work with Brio</Description>
    <PackageProjectUrl>https://github.com/emyxiv/PoseBrowser</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Brio.API" Version="3.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Library\" />
  </ItemGroup>
</Project>
